### ISSUE TITLE
Help understanding the IO processes

### ISSUE THREAD

**Issue by sachaservan** [KULeuven-COSIC/SCALE-MAMBA#10]
Hi, I read through the documentation and am left with a few questions which I hope could get clarified. 
I am specifically trying to understand how the IO stuff works. 

So suppose I would like to have a simple C++ application that has different computers (players) each input a number to the SCALE engine and then have the product of those numbers revealed publicly. This seems fairly straightforward to do in MAMBA, for example, I could do something like:
```
        a=sint.get_private_input_from(0)
        b=sint.get_private_input_from(1)
        c=sint.get_private_input_from(2)
        d = a*b*c
        d.reveal()
```

Now my question is, do I need to create a MAMBA program and then execute each player inside my C++ program and provide input through stdin? I feel like there is a better way of achieving this based on the doc but don't have a clear idea of how. Could you maybe point me in the right direction?  Thanks!

**Comment by NigelSmart** [comment]
If you use the C++ program provided then you just use
stdin, as that is what the default IO class does. If you
want a more complicated application you should
write your own IO class, link it into the correct place
and then link the SCALE libraray against your
own C++ program to do what you want.

Nigel

**Comment by sachaservan** [comment]
Hi @NigelSmart, I'm still struggling to understand how IO works in SM. Any plans on adding the banker's bonus example from SPDZ-2? I think it would be very helpful in understanding the documentation.

**Comment by cnasikas** [comment]
@sachaservan #9

**Comment by cnasikas** [comment]
We implemented an external data importer following: Confidential Benchmarking based on MultipartyComputation at https://github.com/Athena-MHMD/SCALE-MAMBA.

Disclaimer: It is not ready for production yet.
