### ISSUE TITLE
Building SCALE-MAMBA on a Mac

### ISSUE THREAD

**Issue by ChaitanyaKr** [KULeuven-COSIC/SCALE-MAMBA#15]
Hi,
Has either of the contributors or someone else had any experience with building this on a Mac? 
I'm running into issues with cryptopp dependencies, but wouldn't want to roll back to Scale-MAMBA v1.1 (which didn't have cryptopp)

I'm running Mac OS 10.14.3

Thanks,

**Comment by ChaitanyaKr** [comment]
I managed that. 
For somebody else trying the same, `mpir` and `openssl` work just as they do for Linux (remember to use `./Configure darwin64-x86_64-cc --prefix="{mylocal}/openssl"` in place of the usual `./config...`). The brew install of crypto++ (`brew install libcrypto`) works well (and the tar file build from source doesn't).

**Comment by antidb** [comment]
You did run SCALE-MAMBA on Mac ?

I install ed mpir, openssl and cryptopp, but make progs didn't work

`cd src ; make
g++ -Wall -std=c++11 -pedantic -Wextra -g -pthread -I/Users/antidb/SCALE-MAMBA/src -maes -mpclmul -msse4.1 -mavx -march=core2 -DMAX_MOD_SZ=7  -O3  -I/Users/antidb/local/openssl/include  -c Setup.cpp
Setup.cpp: In function 'void init_certs()':
Setup.cpp:103:7: error: 'OPENSSL_INIT_LOAD_SSL_STRINGS' was not declared in this scope
       OPENSSL_INIT_LOAD_SSL_STRINGS | OPENSSL_INIT_LOAD_CRYPTO_STRINGS, NULL);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Setup.cpp:103:7: note: suggested alternative: 'OPENSSL_NO_WEAK_SSL_CIPHERS'
       OPENSSL_INIT_LOAD_SSL_STRINGS | OPENSSL_INIT_LOAD_CRYPTO_STRINGS, NULL);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       OPENSSL_NO_WEAK_SSL_CIPHERS
Setup.cpp:103:39: error: 'OPENSSL_INIT_LOAD_CRYPTO_STRINGS' was not declared in this scope
       OPENSSL_INIT_LOAD_SSL_STRINGS | OPENSSL_INIT_LOAD_CRYPTO_STRINGS, NULL);
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Setup.cpp:102:3: error: 'OPENSSL_init_ssl' was not declared in this scope
   OPENSSL_init_ssl(
   ^~~~~~~~~~~~~~~~
Setup.cpp:102:3: note: suggested alternative: 'OPENSSL_init'
   OPENSSL_init_ssl(
   ^~~~~~~~~~~~~~~~
   OPENSSL_init
make[1]: *** [Setup.o] Error 1
make: [progs] Error 2 (ignored)`

**Comment by ChaitanyaKr** [comment]
Is `openssl` at the right version on your system? It's at `OpenSSL 1.1.0j` for me
