### ISSUE TITLE
Public output cfloat or cfix

### ISSUE THREAD

**Issue by cnasikas** [KULeuven-COSIC/SCALE-MAMBA#18]
Hi,

I am trying to do public output of an sfloat/sfix value but there doesn't seem to be a readily available way of doing this. When I try for example

```
a = sfix(5.0)
cfix.public_output(a.reveal())
```

I get the following error:

`AttributeError: type object 'cfix' has no attribute 'public_output'`

and

```
a = sfix(5.0)
cint.public_output(a.reveal())
```

I get the following error:

`TypeError: unbound method public_output() must be called with cint instance as first argument (got cfix instance instead)`

I understand that `cint.public_output` in only for cint types and, as far I know by reading the documentation, `cfloat` and `cfix` do not provide a public output function. Is there a way to output an `cfloat` or `cfix`

Thanks a lot

**Comment by NigelSmart** [comment]
Use...

a=sfix(5.123)
cc=a.reveal()
cc.print_fix_plain()   

Suggesting sending queries to the email list, we rarely look at the github for issues raised.
