### ISSUE TITLE
Porting Compiler code to Python 3

### ISSUE THREAD

**Issue by sbellem** [KULeuven-COSIC/SCALE-MAMBA#22]
Given that [Python 2 will not be maintained past 2020](https://pythonclock.org/), are there plans to port the Python code to Python 3?

I may be able to help with that effort if needed.

**Comment by rdragos** [comment]
Hi,

I think the future plan is to have a different front-end language than Python (something in Rust). I am not sure about the timeline here...

**Comment by sbellem** [comment]
Hi, thanks for the answer!
