### ISSUE TITLE
Q. (docs): "If a test passes then the program will fail, ..."

### ISSUE THREAD

**Issue by sbellem** [KULeuven-COSIC/SCALE-MAMBA#24]
I do not understand the following wording in the documentation:

https://github.com/KULeuven-COSIC/SCALE-MAMBA/blob/d8bc74e910f531d9514ea267c29bb35a769a9de5/Documentation/Example.tex#L65-L73

More precisely, two things:

1. https://github.com/KULeuven-COSIC/SCALE-MAMBA/blob/d8bc74e910f531d9514ea267c29bb35a769a9de5/Documentation/Example.tex#L68-L71

and

2. https://github.com/KULeuven-COSIC/SCALE-MAMBA/blob/d8bc74e910f531d9514ea267c29bb35a769a9de5/Documentation/Example.tex#L72-L73

**Comment by rdragos** [comment]
Have a look at all Programs/test_* files and you'll see that there are multiple lines containing 'test(x, y)'. See for example [this](https://github.com/KULeuven-COSIC/SCALE-MAMBA/blob/master/Programs/test_comparison/test_comparison.mpc#L16).

You can see that test(x,y) actually tests whether value x computed using SCALE is the same with the one feed by the compiler value y. What happens underneath is that SCALE runs the MPC protocols machinery and then compares it with the value emulated in python.

**Comment by sbellem** [comment]
Ok thanks. I will need to look closer and learn more about the system as I still do not understand. More precisely:

test passes --> program fails

Somehow, I normally assume that if a test passes then the associated program works properly.
