### ISSUE TITLE
MASCOT in SCALE-MAMBA

### ISSUE THREAD

**Issue by jayavanth** [KULeuven-COSIC/SCALE-MAMBA#25]
When you refer to SPDZ in the documentation, are you actually referring to MASCOT? For example in section 3.2
> All channels will be TLS encrypted. For SPDZ this is not needed, but..

Also, are there any examples/tests for MASCOT?

**Comment by mkskeller** [comment]
SCALE-MAMBA doesn't implement MASCOT, only SPDZ. The online phase is the same, but the offline phase uses oblivious transfer in MASCOT and somewhat homomorphic encryption on SPDZ. For an implementation of MASCOT, see https://github.com/data61/MP-SPDZ
