### ISSUE TITLE
Could not open log file error

### ISSUE THREAD

**Issue by ChaitanyaKr** [KULeuven-COSIC/SCALE-MAMBA#3]
I've been trying out the framework for using multiple geographically distributed VMs and while I'm able to compile and run the `Programs/tutorial` exercise, they always end with the following error:
```
MatrixMeasurement: Could not open log file '/root/SCALE-MAMBA/MATRIX/logs/offline*3*129.log'
```
Such a directory doesn't exist. Did I miss something during `make`?

**Comment by rdragos** [comment]
Why do you use the 'matrix' branch? You should use the 'master' one.

**Comment by ChaitanyaKr** [comment]
I was using the `matrix` branch because the documentation to run things and the directions/steps were on it (per the discussion we had [here](https://github.com/KULeuven-COSIC/SCALE-MAMBA/issues/1#issuecomment-451673990)).
I see that the `master` branch doesn't have a MATRIX directory; won't I face the same error there as well? Also, is the name MATRIX same as the [MATRIX project](https://github.com/cryptobiu/MATRIX), or is this a different thing altogether?

**Comment by rdragos** [comment]
The 'matrix' branch is meant for AWS usage inside the MATRIX project you
mentioned.

Follow the same steps but in the 'master' branch. To avoid confusion I also
wrote a blogpost on installing the libraries in SCALE:
https://rdragos.github.io/2019/01/07/scale/

**Comment by ChaitanyaKr** [comment]
Thanks, that worked. 
So is there an explicitly created logs directory? 
I could always write the output of the commands (`./compile.py ...`, `./Player.x ...`) to a destination myself, but I was wondering if there's some feature for me to enhance the log level to get better insights into the computation runs.

**Comment by rdragos** [comment]
Indeed, right now the best you can hope for is piping to a file and then do a grep search.
