### ISSUE TITLE
terminate called after throwing an instance of 'sending_error' what(): Sending error

### ISSUE THREAD

**Issue by uomprogrammer** [KULeuven-COSIC/SCALE-MAMBA#33]
Hello,
I have set the SCALE_MAMBA and run the tutorial correctly. Then I tried to run the full threshold for 300-bit prime and it seems there is an issue.
./Setup.x 
What do you want to set up?
        1) Certs
        2) Secret Sharing
        3) Conversion circuit for LSSS<->GC computations
        4) All three

Enter a number (1-4)..
2
Number of players = 3

Choose which LSSS you want...
        1) Full Threshold
        2) Shamir
        3) Replicated
        4) General Q2 MSP
Enter a number (1-4)..
1
Do you want me to find a prime for the LSSS, or do you want to try one yourself?
        0) You find one
        1) I will enter one
0
What bit length of modulus do you want for secret sharing? (16-1024)
300-1024
N  = 65536
U = 16  V = 8
p  = 1018517988167243043134222844204689080525734196832968125318070224677190649881668353106771969 : 300 300 1
p0 = 5136851466355833503165029182500125649951503713694505722166289944403058744430742990345377476833582471901350555523611540735370539306820120960085756611964727392534398116336371677921546638558908903585247320866817 : 692 691 1
p1 = 645562469521727147413996480399471100692445159314385327833560172764242816853975509929526276265171502063883908339243548673 : 399 399 1
Finished setting up secret sharing. 
The underlying MSP is...
3 3
1 0 0 
0 1 0 
0 0 1 

3
1 1 1 

./Setup.x 
What do you want to set up?
        1) Certs
        2) Secret Sharing
        3) Conversion circuit for LSSS<->GC computations
        4) All three

Enter a number (1-4)..
3
Producing conversion circuit LSSS to GC for prime 1018517988167243043134222844204689080525734196832968125318070224677190649881668353106771969
nBits= 300 nzeros0=212 nzeros1=408
Going to try and simplify circuit a bit
        Please be a little patient, it is worth it in the long run :-) 
0 : nwires : 6570    ngates : 6166    and gt : 2273
1 : nwires : 6564    ngates : 6160    and gt : 2272
2 : nwires : 6562    ngates : 6158    and gt : 2272
3 : nwires : 6560    ngates : 6156    and gt : 2272
4 : nwires : 6558    ngates : 6154    and gt : 2272
5 : nwires : 6556    ngates : 6152    and gt : 2272
6 : nwires : 6554    ngates : 6150    and gt : 2272
7 : nwires : 6552    ngates : 6148    and gt : 2272
.
.
.
246 : nwires : 4984    ngates : 4580    and gt : 1872
247 : nwires : 4982    ngates : 4578    and gt : 1872
248 : nwires : 4980    ngates : 4576    and gt : 1872
249 : nwires : 4978    ngates : 4574    and gt : 1872
Completed the conversion

./compile.py Programs/tutorial
Compiling program in Programs/tutorial
tutorial
p = 1018517988167243043134222844204689080525734196832968125318070224677190649881668353106771969
Prime size: 296
Default bit length: 64
Default statistical security parameter: 40
Under Over Flow flag:  True
Compiling file Programs/tutorial/tutorial.mpc
Compiling basic block tutorial-0--0
Compiling basic block tutorial-0-pre-start-timer-1
Compiling basic block tutorial-0-post-start-timer-2
Compiling basic block tutorial-0-pre-stop-timer-3
Compiling basic block tutorial-0-post-stop-timer-4
Processing tape tutorial-0 with 5 blocks
Processing basic block tutorial-0-pre-start-timer-1, 1/5, 1 instructions
Processing basic block tutorial-0-post-start-timer-2, 2/5, 341 instructions
Program requires 2 rounds of communication
Program requires 30 invocations
Processing basic block tutorial-0-pre-stop-timer-3, 3/5, 1 instructions
Processing basic block tutorial-0-post-stop-timer-4, 4/5, 10 instructions
Tape register usage: defaultdict(<function <lambda> at 0x7f98798bf350>, {'sr': 0, 'c': 40, 'r': 0, 's': 120, 'sb': 0})
modp: 40 clear, 120 secret
Re-allocating...
Compile offline data requirements...
Tape requires 10 triples in modp
Tape requires prime bit length 0
Program requires: {('modp', 'triple'): 10}
Memory size: defaultdict(<function <lambda> at 0x7f98798bf0d0>, {'sr': 8192, 'c': 8192, 'r': 8192, 's': 8192, 'sb': 8192})
Compiling basic block tutorial-0-memory-usage-4
Memory of type 'sr' of size 8192
Memory of type 'c' of size 8192
Memory of type 'r' of size 8192
Memory of type 's' of size 8192
Memory of type 'sb' of size 8192
Writing to Programs/tutorial/tutorial.sch
Writing to Programs/tutorial/tutorial-0.bc
Writing to Programs/tutorial/tutorial-0.bc

time ./Player.x 0 Programs/tutorial
(Min,Max) number of ...
        (0,infty) multiplication triples
        (0,infty) square pairs
        (0,infty) bits
0
127.0.0.1
Player1.crt
P1
1
127.0.0.1
Player2.crt
P2
2
127.0.0.1
Player3.crt
P3

p=1018517988167243043134222844204689080525734196832968125318070224677190649881668353106771969
Opening file Programs/tutorial/tutorial.sch
Number of online threads I will run in parallel =  1
Number of program sequences I need to load =  1
Loading program 0 from Programs/tutorial/tutorial-0.bc
tutorial-0 needs more gfp memory, resizing to 8192
tutorial-0 needs more Share memory, resizing to 8194
tutorial-0 needs more integer memory, resizing to 8192
tutorial-0 needs more aBitVector memory, resizing to 8192
All connections now done
Setting up threads
I am player 0 in thread 0
I am player 0 in thread 1
I am player 0 in thread 2
I am player 0 in thread 3
I am player 0 in thread 4
I am player 0 in thread 10000
I am player 0 in thread 10001
Waiting for thread 0 to be ready
I am player 0 in thread 20000
I am player 0 in thread 20001
Set up player 0 in thread 20001 
Set up player 0 in thread 2 
Set up player 0 in thread 0 
Set up player 0 in thread 4 
Doing online for player 0 in online thread 0
Set up player 0 in thread 20000 
Set up player 0 in thread 10000 
Set up player 0 in thread 10001 
Set up player 0 in thread 1 
Set up player 0 in thread 3 
Finished Base-OTs
Starting online phase
Signal online thread ready 0
terminate called after throwing an instance of 'sending_error'
  what():  Sending error
Aborted (core dumped)

**Comment by uomprogrammer** [comment]
I was able to pass this error by changing the CONFIG and then recompile again using make progs. Then went all over the steps again and tried to get it to work for full threshold and 256 bits prime. I got this error:
./Player.x 0 Programs/tutorial
(Min,Max) number of ...
        (0,infty) multiplication triples
        (0,infty) square pairs
        (0,infty) bits
0
127.0.0.1
Player1.crt
P1
1
127.0.0.1
Player2.crt
P2
2
127.0.0.1
Player3.crt
P3


p=57896044618658097711785492504343953926634992332820282019728792003956589723649
Opening file Programs/tutorial/tutorial.sch
Number of online threads I will run in parallel =  1
Number of program sequences I need to load =  1
Loading program 0 from Programs/tutorial/tutorial-0.bc
tutorial-0 needs more gfp memory, resizing to 8192
tutorial-0 needs more Share memory, resizing to 8192
tutorial-0 needs more integer memory, resizing to 8192
tutorial-0 needs more aBitVector memory, resizing to 8192
All connections now done
Setting up threads
I am player 0 in thread 0
I am player 0 in thread 1
I am player 0 in thread 2
I am player 0 in thread 3
I am player 0 in thread 4
I am player 0 in thread 10000
I am player 0 in thread 10001
I am player 0 in thread 20000
Waiting for thread 0 to be ready
I am player 0 in thread 20001
Set up player 0 in thread 0 
Set up player 0 in thread 4 
Doing online for player 0 in online thread 0
Set up player 0 in thread 3 
Set up player 0 in thread 10001 
Set up player 0 in thread 10000 
Set up player 0 in thread 20000 
Set up player 0 in thread 20001 
Set up player 0 in thread 1 
Set up player 0 in thread 2 
Finished Base-OTs
terminate called after throwing an instance of 'receiving_error'
  what():  Receiving error
Aborted (core dumped)

**Comment by NigelSmart** [comment]
Please post this to the email list, do not use issues in github as we rarely look here. If you post to the email list you are likely to get a quick response from the team monitoring this.
