### ISSUE TITLE
Fixed seed in key(?) generation?

### ISSUE THREAD

**Issue by lumip** [KULeuven-COSIC/SCALE-MAMBA#39]
Browsing through the code of `src/Setup.cpp` it seems that there are some keys generated from a PRNG instantiated with a fixed seed. I'm referring to [line 476](https://github.com/KULeuven-COSIC/SCALE-MAMBA/blob/53dad91c9669fac2e327e25cbcb5420fa6ee2939/src/Setup.cpp#L476) of the file, where the PRNG `G` is seeded and then apparently subsequently used while generating and writing MAC (keys?) into `Data/MKey-.key` files.
Maybe I'm reading/interpreting the code wrong and this is not an issue (maybe the generated values are not security relevant after all?), but I doubt so and wanted to raise it for review and comments.

**Comment by NigelSmart** [comment]
See random.cpp line 24...
