### ISSUE TITLE
Running IO_demo

### ISSUE THREAD

**Issue by ChaitanyaKr** [KULeuven-COSIC/SCALE-MAMBA#4]
Hi,
I've been trying to run the IO_demo.mpc file across four players (indexed 0-3), but it gets stuck, at the `Enter value on channel 2000 :` line.

- If I input the values 1,2,3,4 for players 0-3 respectively, it proceeds for player 3 until `Opening channel 20` and then nothing happens for any player
- If I input the values 10,20,30,40, it proceeds for player 2 until `Opening channel 20` and then nothing happens for any player

Since this line seems to be coming from the Input_Output_Simple.cpp file, I'm not quite clear what am I expected to key in here. Any ideas, pointers ?

**Comment by NigelSmart** [comment]
What type of LSSS are you using. If a full threshold one then
you also need to add the MAC values when entering a Share value

The input/output of shares is really for when someone wants to
do external storage of shares from the system. In normal usage
you really just want to enter values from players.

So in this case you could delete the following lines from IO_demo.mpc


open_channel(1000)
# Write some data to file
outp = [sint(1), sint(2), sint(3), sint(4)]
output_shares(1000,*outp)
close_channel(1000)

a=open_channel(2000)
print_ln("Return Value From Open_Channel 2000 = %s",a)
open_channel(3000)
print_ln("Enter a single share from each player")
inp=[sint()]
input_shares(2000,*inp)
output_shares(3000,*inp)
close_channel(2000)
close_channel(3000)


Nigel

**Comment by ChaitanyaKr** [comment]
Thanks, it almost worked after commenting out those lines. It was terminated:

`terminate called after throwing an instance of 'inconsistent_inputs' `
`what():  The players inputs were inconsisent in the IO input routines`
`Aborted (core dumped)`


Could you please provide me with an example? The bit about handling input from files will also be useful since, in my setup, the parties would need to load data from files.

**Comment by NigelSmart** [comment]
When entering data which is PUBLIC, this should be consistent
between all parties; i.e. if data is different when entering
public data then it crashes.

This mirrors what would happen if each party loads public
data from a local file each. If the local files are different
something has gone wrong
