### ISSUE TITLE
about PRSS implementations

### ISSUE THREAD

**Issue by xiexiangplaton** [KULeuven-COSIC/SCALE-MAMBA#40]
Hi, there

When using the source code of SCALE-MAMBA, we found some strange problems.

Let n, t such that the n C t is bigger than the fixed threshold (50), the next_share function in PRSS will always return shares of 0. I know that the PRSS is instead of an interactive protocol, but the output is still not normal.

We also check the triples and squares generated offline in the above case. The triples are normal, but it always return 0 shares in squares,  which we think something is not normal there.

Look forward to your reply.

Best

**Comment by abdelrahamanaly** [comment]
HI,
Have you tried posting your questions on the mailing list? It is more
regularly maintained:
https://groups.google.com/forum/#!forum/spdz

**Comment by xiexiangplaton** [comment]
Just submitted the request to join the group.

> HI, Have you tried posting your questions on the mailing list? It is more regularly maintained: https://groups.google.com/forum/#!forum/spdz

**Comment by NigelSmart** [comment]
Just fixed
