### ISSUE TITLE
MAC regarding comparison

### ISSUE THREAD

**Issue by ziyao002** [KULeuven-COSIC/SCALE-MAMBA#41]
Hi can I know how to obtain the MAC on the result of comparison in SCALE-MAMBA? Because comparison function returns the [sign bit of input], if the input is MAC, then we can only obtain the [sign bit of MAC] instead of {[MAC(0)], [MAC(1)]}. Thank you so much!

**Comment by NigelSmart** [comment]
You should not be accessing the MAC within a Mamba computation. Imagine you are running in Shamir mode, then there are no MACs, so accessing the MAC from within Mamba makes no sense
