### ISSUE TITLE
Bug in vector construction of ints

### ISSUE THREAD

**Issue by ThomasTNO** [KULeuven-COSIC/SCALE-MAMBA#44]
Hi,

Currently I am not able to construct a vector of sints/cints. Is this unsupported?

```sint(sint(1), size=100)```
Does not work. `Compiler.exceptions.CompilerError: Mismatch in vector size`

This does work, however:
```sfix(sfix(1), size=100)```

What would be needed to support this in the compiler?

**Comment by kc1212** [comment]
would something like `sint.Array(100)` work for you? see section 7.2.6 of the documentation
