### ISSUE TITLE
after make circuits  command   error:   ../src/libMPC.a: No such file or directory

### ISSUE THREAD

**Issue by Marslanali** [KULeuven-COSIC/SCALE-MAMBA#46]
Hi,

I am compiling the circuits using `make circuits`, however, I am unable to run it successfully, it sounds like the MakeFile inside the Circuits directory is looking for  ` ../src/libMPC.a: `.

Do I need to compile first src, using `make`. Also there is no CONFIG.mine file exist, however the MakeFile insider Circuits is looking for ../CONFIG.mine.

Can any one please comment, how to compile circuit using `make` successfully? I am using Ubuntu 16.04LTS

Thanks and looking forward.

Arslan

**Comment by rdragos** [comment]
I think you need to copy the original CONFIG file to CONFIG.mine and then
try to compile

**Comment by Marslanali** [comment]
I accidentally-closed this issue. I tried to copy the original CONFIG file to CONFIG.mine.

And then `make circuits`, but still I got same error. Any insight on this issue? Attached is my terminal screenshots after `make circuits`

![make](https://user-images.githubusercontent.com/19324754/86369437-dfdb5b80-bc97-11ea-867f-f5557469c6d4.png)

**Comment by Marslanali** [comment]
-

**Comment by Marslanali** [comment]
My issue is solved now.!!
