### ISSUE TITLE
Code not working sucessfully for two party

### ISSUE THREAD

**Issue by CryptoMeena** [KULeuven-COSIC/SCALE-MAMBA#47]
I have written sample two party code for addition by taking input from command prompt. But it does not work for two party setting. It gets stuck after online phase and process gets killed. I have imported the NetworkData.txt and SharingData.txt from the folder /Auto-Test-Data/20/.  The following is the two party code.

print_ln("Player zero enter a  number")
a=sint.get_private_input_from(0,1000)
print_ln("Player one enter a  number")
b=sint.get_private_input_from(1,1000)
c=a*b
print_ln("The product is being sent to player one %s",c.reveal())
close_channel(1000)

**Comment by rdragos** [comment]
You also need to call open_channel before inputting data.

**Comment by CryptoMeena** [comment]
Still giving error. The following is the code
open_channel_with_return(1000)
print_ln("Player zero enter a  number")
a=sint.get_private_input_from(0,1000)
print_ln("Player one enter a  number")
b=sint.get_private_input_from(1,1000)
c=a*b
print_ln("The product is being sent to player one %s",c.reveal())
close_channel(1000)






The following is the error
 ./Player.x  0 Programs/add_IO/
(Min,Max) number of ...
	(0,infty) multiplication triples
	(0,infty) square pairs
	(0,infty) bits
0
127.0.0.1
Player1.crt
P1
1
127.0.0.1
Player2.crt
P2


p=2148728833
sm::0:: loading certificate from Cert-Store/Player1.crt
Opening file Programs/add_IO//add_IO.sch
Number of online threads I will run in parallel =  1
Number of program sequences I need to load =  1
Loading program 0 from Programs/add_IO//add_IO-0.bc
All connections now done
Setting up threads
I am player 0 in thread 0
I am player 0 in thread 1
Waiting for thread 0 to be ready
I am player 0 in thread 4
I am player 0 in thread 10000
I am player 0 in thread 10001
I am player 0 in thread 20000
I am player 0 in thread 3
I am player 0 in thread 2
I am player 0 in thread 20001
Set up player 0 in thread 3 
Set up player 0 in thread 4 
Doing online for player 0 in online thread 0
Set up player 0 in thread 10001 
Set up player 0 in thread 2 
Set up player 0 in thread 0 
Set up player 0 in thread 1 
Set up player 0 in thread 10000 
Set up player 0 in thread 20000 
Set up player 0 in thread 20001 
Finished Base-OTs
Starting online phase
Signal online thread ready 0

**Comment by CryptoMeena** [comment]
open_channel(1000) gives the following error.

./compile-mamba.py Programs/add_IO/
Compiling program in Programs/add_IO/
add_IO
p = 2148728833
Prime size: 32
Default bit length: 24
Default statistical security parameter: 6
Under Over Flow flag:  True
Compiling file Programs/add_IO/add_IO.mpc
Compiling basic block add_IO-0--0
Traceback (most recent call last):
  File "./compile-mamba.py", line 76, in <module>
    main()
  File "./compile-mamba.py", line 73, in main
    compilation()
  File "./compile-mamba.py", line 58, in compilation
    debug=options.debug)
  File "/home/meena/meena/projects/SMPC/SCALE-MAMBA-master/Compiler/compilerLib.py", line 37, in run
    execfile(prog.infile, VARS)
  File "Programs/add_IO/add_IO.mpc", line 1, in <module>
    open_channel(1000)
  File "/home/meena/meena/projects/SMPC/SCALE-MAMBA-master/Compiler/instructions_base.py", line 468, in __init__
    self.check_args()
  File "/home/meena/meena/projects/SMPC/SCALE-MAMBA-master/Compiler/instructions_base.py", line 510, in check_args
    % (e.arg, self) + '\n' + e.msg)
Compiler.exceptions.CompilerError: Invalid argument "1000" to instruction: open_channel 1000
Invalid register argument

**Comment by rdragos** [comment]
Seems like the correct syntax is having `open_channel_with_return` as you specified. It might be that the program waits for some input, how do you handle the input part in the C++ code?

**Comment by CryptoMeena** [comment]
We need to take the input from player at his terminal. In that perspective I have written following code. This works fine for 3 players but not for two players.

print_ln("Player zero enter a  number")
a=sint.get_private_input_from(0,1000)
print_ln("Player one enter a  number")
b=sint.get_private_input_from(1,1000)
c=a*b
print_ln("The product is being sent to player one %s",c.reveal())
close_channel(1000)

**Comment by rdragos** [comment]
If for the 2 players you're referring to the dishonest majority case then
you need to wait a bit more as it takes some time for the preprocessing
queues to load. I would just put a print statement to see when the first
batch of input masks is produced (then you know that it's the time to input
stuff).
