### ISSUE TITLE
Error after an hour of running

### ISSUE THREAD

**Issue by asifmallik** [KULeuven-COSIC/SCALE-MAMBA#50]
I am running some benchmark with SCALE-MAMBA and I noticed that for three of my tests that were supposed to exceed an hour of computation seems to exit with an error suspiciously around the one hour mark: "terminate called recursively" and "terminate called after throwing an instance of 'receiving_error' terminate called recursively" were two variations of the error. So, I was wondering whether such a limit is hard coded or this is just a coincidence. I could not find this being mentioned in the documentation.

**Comment by NigelSmart** [comment]
Nope. Looks indeed weird.

As usual the obvious questions are...

a) What access structure/secret sharing scheme
b) How many machines are you actually using
    - If one then you might be running out of memory if it is of
      too low a spec
c) gdb is your friend (and ours). If its not a b problem then
   we need to see which line number it fell over on.

d) Use the mailing list not github issues please. More people monitor that

**Comment by asifmallik** [comment]
Thank you, I will follow up on this on the mailing list
