### ISSUE TITLE
High usage of RAM

### ISSUE THREAD

**Issue by tilenmarc** [KULeuven-COSIC/SCALE-MAMBA#51]
Dear authors,
I was testing and studying your implementation and in particular I was wondering why running even simple programs takes so much RAM. After bounding the production of triplets, squares, bits (which by the way, even if you bound it with a very small number still produces tens of thousands of them), I noticed that maybe the bigger consumer of memory is aBitFactory. I found a parameter `max_aBit_queue` in `config.h` file that should bound the production of aBits, but it seems that even before this bound is applied, functions `aBitFactory::Initialize` and `aBitFactory::tune` are called that produce millions of aBits.
Further studying these functions in noticed that they use some magical values `max_l = 1131072`,  `l= 16384`. Since there is no comments in the code that would explain what these functions do and what are these values, I am asking if you could explain it and also tell me if they can be modified to bound the memory consumption.
Btw, I was running SCALE as set up with Auto-Test-Data/1/ if this is important. But I wonder what happens also in the malicious setting. 
Best regards,
Tilen

**Comment by NigelSmart** [comment]
NOTE: USE THE MAILING LIST NOT GITHUB ISSUES....


If you dont use garbled circuit routines you can turn off the
aBits production by passing
  -dOT
to Player.x

Basically the aBits are the pre-processing needed to cope with GC
operations (arithmetic on sregint's and anything else using GC),
plus all daBit style operations.  

> Btw, I was running SCALE as set up with Auto-Test-Data/1/ if this is
> important. But I wonder what happens also in the malicious setting.

Every setting is malicious in SCALE

**Comment by tilenmarc** [comment]
Ok, thanks for the answer! But what about the magic constants in the code I mentioned? Where do that numbers come from?
