### ISSUE TITLE
compiler difference between SPDZ-2 and SCALE-MAMBA

### ISSUE THREAD

**Issue by cszz12** [KULeuven-COSIC/SCALE-MAMBA#6]
Hi,

It seems that there are more advanced test in SPDZ-2 Programs/Source than that in SCALE-MAMBA Programs. I tried to compile some with MAMBA's compiler and found some error.
Is there any difference in the compiler or something incompatible?

Thanks a lot!

**Comment by cszz12** [comment]
If I compile bankers_bonus, it says
...../SCALE-MAMBA/Compiler/compilerLib.py", line 37, in run
    execfile(prog.infile, VARS)
  File "Programs/bankers_bonus/bankers_bonus.mpc", line 20, in <module>
    from Compiler.instructions import listen, acceptclientconnection
ImportError: cannot import name listen

**Comment by rdragos** [comment]
Yes, the language is sometimes incompatible because (some) things are done differently in S&M.

For example, when parties want to provide input to S&M they do it via the special API present here https://github.com/KULeuven-COSIC/SCALE-MAMBA/blob/master/src/Input_Output/Input_Output_Base.h In SPDZ-2 you cannot find this.

Other example, as you figured it out is the bankers_bounus demo. In S&M you need to implement the special protocol ( https://eprint.iacr.org/2015/1006 )for providing inputs to the MPC engine using the Input_Output wrapper - that's a bit more difficult to do. Unfortunately this is not on our priorities list right now...

**Comment by cszz12** [comment]
Thanks Dragoș for the reply!
Sorry I don't know too much about MPC. If I understand correctly, the problem is that there doesn't exist a bridge between bankers_bonus demo's inputs and MPC engine, not possible right now with Input_Output wrapper?
Is it hard to implement? If not, I can contribute some code.

What about some more complex sample programs? I see that samples in S&M may be too simple as a tutorial?

**Comment by NigelSmart** [comment]
Indeed the idea with SM is that the user needs to create their own wrapper for an application. In SPDZ2 each application ended up doing something very different leading to code bloat.

The new IO stuff is more general but requires more engineering on the user side as opposed to huge amounts of engineering on our side. In the long run the new interface is easier to extend etc and supports more applications
Yours 

Nigel
--

**Comment by NigelSmart** [comment]
All client connection is now to be done by the application as opposed to our system. This avoids code bloat. But does mean bankers bonus no longer compiles as an application 
Yours 

Nigel
--

**Comment by cszz12** [comment]
Thanks for the reply, Professor Smart!
Interesting trade-off! However, this ends up more time consuming for end users, but does save space&improve generality for the core lib. 
Would it be better if there were one plugin/client_lib, or something to be reusable?

**Comment by NigelSmart** [comment]
Actually makea it easier for end users as there is now a clean interface to build applications on top off which does not require altering the base library. 

Think of what would happen if everytime in C++ if you wanted to use something  lime streams you had to edit gcc internally.  That is what the old system was like. 

The new system is a simple API which you write do.  If bankers bonus was implemented again then the code size would now be about 50% smaller. So easing developers efforr
Yours 

Nigel
--

**Comment by cszz12** [comment]
sounds reasonable. Let me give it a try.
Thanks!
