### ISSUE TITLE
Reading from and Writing to files

### ISSUE THREAD

**Issue by ChaitanyaKr** [KULeuven-COSIC/SCALE-MAMBA#7]
Hi,
I see that the documentation mentions about sharing input and output, however, I could not find straightforward examples or APIs where I could pass in a _path/to/filename/_ and read from or write to it. 
Could you please provide an example, or let me know if this isn't supported?

Thanks

**Comment by NigelSmart** [comment]
You need to write this yourself in C++ and then connect your
external application to the SCALE engine using the IO class.
You use this by linking your application against the SCALE library
and then calling SCALE programmatically.

Think of SCALE as a microprocessor, and then your application
you build around it as an operating system.

The MAMBA language allows you to create machine code, which
you then need to execute via your OS in an application.

The command line stuff to execute MAMBA compiled byte codes
is really just for testing the output of the compiler, it is not meant
as a "final application"

Nigel
